name: image coloring
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取源码
        uses: actions/checkout@master

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 初始化
        run: pnpm install

      - name: 打包
        run: pnpm run build

      - name: 传输包
        run: scp -r dist root@47.108.79.61:/root
